### ISSUE TITLE
Alter not implemented? 

### ISSUE THREAD

**Issue by cccc1999** [mardambey/mypipe#1]
Hi there, 

This project looks interesting, but want to double check that to my understanding, the alter statement has not been implemented yet? 

Thanks!

**Comment by mardambey** [comment]
Hi @cccc1999!

You're right, alter is not implemented yet.

That being said, over the last few days (7ccf352 and dcbdb35) I've starting putting in an implementation and some tests for handling alter. When publishing "generically" to Kafka we now support the ability to detect an alter, refresh the table's meta data, and detect the addition or removal of columns (actually, we just re-fetch the metadata from the database). This means that the downstream Kafka topic that is receiving "generic" Avro records can now deal with the addition and removal of columns.

I haven't done any work for the "specific" Kafka producer (which uses the Avro schema repository to find the exact schema matching your table) but hope to get some more time to work on it soon.

Contributions are obviously also more than welcome! (=

**Comment by cccc1999** [comment]
Thanks @mardambey  for the detailed explanation. Good to know that alter is under way :+1:

**Comment by mardambey** [comment]
@cccc1999 take a look at 2dbf095b77305638b102b6da0880f27615a88747 and 79af971cd25cc6ebf426afb5124c1458bf4d5568. We now propagate alter events and we can refresh schema definitions accordingly in Kafka producers.

Thanks for asking for this feature (=
