### ISSUE TITLE
Handle 'empty' transactions more careful to avoid crashing when STATEMENT binlog occurs

### ISSUE THREAD

**Issue by yeputons** [mardambey/mypipe#16]
I have the following situation:
1. DB is located on Amazon RDS
2. Binlog is enabled and set to `ROW` format
3. Amazon RDS has their own table `mysql.rds_heartbeat2`, which is updated every several minutes (for replication purposes, I guess)
4. These changes get into binlog
5. Binlog format can be configured per session. When Amazon updates this table, they do it in 'STATEMENT' mode for some reason.
6. Therefore, binlog ends up with:
   - `BEGIN`
   - 'Query' record, which modifies the table (`INSERT INTO ... ON DUPLICATE KEY UPDATE ...`)
   - `COMMIT`
7. Mypipe ignores that query record and fails, because it looks like an empty transaction, while it clearly is not.

Although it's possible to ensure that `ROW` format is used across the application, I doubt it's possible to convince Amazon to change their update mode (looks like it's explicitly specified and they should have reasons for that). So, my suggestion is to handle two cases:
1. Transaction which contains 'Query' statements, but no row updates. Make a separate overridable handler for them (which calls `handleEventError` by default), so user can ignore some of these transactions. I guess it's also a good idea to 'accumulate' queries of transaction (in a list of strings or something), so user have some information about it.
2. Other 'empty' transactions. Process as previously.

**Comment by yeputons** [comment]
By the way, you can reproduce that problem locally by running that sequence of queries:

```
CREATE TABLE something_strange (value INT);
SET SESSION binlog_format = 'STATEMENT';
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
INSERT INTO something_strange VALUES (1);
```

**Comment by mardambey** [comment]
@yeputons take a look at 7b9fab1728950ab3c593bbd2d5a28aa46f48950c. Does that sort this issue out for you?

**Comment by yeputons** [comment]
@mardambey I think so, thank you! Will try that tomorrow and close the issue if everything's ok.

**Comment by yeputons** [comment]
@mardambey It works, I have several other suggestions:

Shouldn't `quit-on-empty-mutation-commit-failure` be `true` by default to be compatible with previous behavior?

I also don't think that logging unknown queries on 'warning' level is a good idea - sometimes they're totally legitimate and known. So, my suggestion is to do that only if no transaction is in progress. Otherwise, these queries will be processed by `handleEmptyCommitError`

**Comment by yeputons** [comment]
@mardambey Thank you!
