### ISSUE TITLE
BinaryLogConsumerListener.onMutation with a sequence of mutations is unused by mypipe

### ISSUE THREAD

**Issue by yeputons** [mardambey/mypipe#17]
For example, it would be useful to have it called for transactions, instead of several consequential single `onMutation`

**Comment by mardambey** [comment]
Thanks for 6b7256135a514f7897165beb1865aa0e9dcab4fe! Awesome work (=

Added as the default behavior (e8d4942c645685eb9d4a90638201a66635d3de41).
