### ISSUE TITLE
Why no `handleDisconnect`?

### ISSUE THREAD

**Issue by yeputons** [mardambey/mypipe#21]
Stub for `onDisconnect` event is <a href="https://github.com/mardambey/mypipe/blob/486f6cbbc84212f7d8096d2376c6ae98d1399c8d/mypipe-api/src/main/scala/mypipe/mysql/AbstractMySQLBinaryLogConsumer.scala#L35-L36">registered</a>, but it does nothing:

```
    override def onDisconnect(client: BinaryLogClient): Unit = {
      // FIXME: call this properly
      //handleDisconnect()
    }
```

What was the problem with `handleDisconnect()`?

**Comment by mardambey** [comment]
@yeputons I had left this out during a refactor, I've added it back in.
