### ISSUE TITLE
when i execute ./sbt package it hangs with no replay

### ISSUE THREAD

**Issue by yester354** [mardambey/mypipe#23]
Hi
   when  i execute ./sbt package it hangs with no replay. I had tried many times. maybe there some problem with my internet.how i can handle this problem without executing sbt package

**Comment by mardambey** [comment]
It's a bit difficult to help you out without seeing anything. Could you perhaps try running your own version of the sbt launcher? Otherwise, you have to try and debug the sbt launcher present with mypipe.

Hope this helps.
