### ISSUE TITLE
using mypipe to dump the whole db to kafka

### ISSUE THREAD

**Issue by bbnsumanth** [mardambey/mypipe#27]
Can someone suggest how to use mypipe to do  a  dump from mysql to a kafka topic and then add the changes to the same topic from then on.Any suggestions on this will be very helpful to me .Thanks in advance.

**Comment by parsnips** [comment]
If you have all the bin logs stored on you target mysql server, I presume it would be as simple as configuring mypipe to start with the first bin file, at position zero with https://github.com/mardambey/mypipe/blob/master/mypipe-api/src/main/scala/mypipe/mysql/AbstractMySQLBinaryLogConsumer.scala#L46-L54

**Comment by mardambey** [comment]
Closing this, we'll follow up in #28.
