### ISSUE TITLE
StdoutProducer printing lines without row data

### ISSUE THREAD

**Issue by andrioni** [mardambey/mypipe#3]
Hi, whenever I create a new table (for tests) while mypipe is already running, the StdoutProducer fails to print the row data:

```
131150 [mypipe-akka.actor.default-dispatcher-4] INFO mypipe.api.Conf$ - Saving binlog position for pipe stdout/localhost:3306 -> mysql-bin.000001:2097
131158 [mypipe-akka.actor.default-dispatcher-4] INFO mypipe.producer.stdout.StdoutProducer -
INSERT INTO teste.teste2 () VALUES ()
151151 [mypipe-akka.actor.default-dispatcher-4] INFO mypipe.api.Conf$ - Saving binlog position for pipe stdout/localhost:3306 -> mysql-bin.000001:2310
151159 [mypipe-akka.actor.default-dispatcher-4] INFO mypipe.producer.stdout.StdoutProducer -
INSERT INTO teste.teste2 () VALUES ()
241151 [mypipe-akka.actor.default-dispatcher-4] INFO mypipe.api.Conf$ - Saving binlog position for pipe stdout/localhost:3306 -> mysql-bin.000001:2849
241159 [mypipe-akka.actor.default-dispatcher-4] INFO mypipe.producer.stdout.StdoutProducer -
INSERT INTO teste.foo () VALUES ()
UPDATE teste.foo SET () Some(WHERE ())
```

Did I forget to configure anything?

**Comment by mardambey** [comment]
Hi @andrioni, I tried reproducing this however I could not.

I created tables after starting up mypipe and inserts showed up OK on the stdout producer.  Can you get mypipe to work for you for any tables at all, even those that are there before you fire up mypipe?

Cheers!

**Comment by andrioni** [comment]
Yes, it worked fine for another test table I created before firing up mypipe. I'm going to try it today on a fresh server to see if maybe I misconfigured anything (which is pretty likely).
