### ISSUE TITLE
Event filtering for multiple db's and rows

### ISSUE THREAD

**Issue by bbnsumanth** [mardambey/mypipe#30]
How to set include-event-condition for multiple databases and tables ?

**Comment by mardambey** [comment]
The value of `include-event-condition` is a string that contains valid Scala code. You can use ANDs (&&) and ORs (||), or you can even use regexes. Keep in mind that these checks will run for every incoming event.

**Comment by bbnsumanth** [comment]
thanks for ur reply,I tweaked ur code little bit so that I'm passing a list of db_table names in config file.In code,for every event i'm checking where the list contains that event or not.
Few more changes that i added to the fork of mypipe:
1)added avroGen:avro schema generator from metadata.
2)custom BinLogPosition through application.conf file.(by setting this to start binlog position ,I can consume all the binlogs available in a mysql db)
3)added KafkaJsonProducer,stdoutJsonProducer
4)added kafkaAvroproducer for confluent platform,so that in combination with avroGen,we can produce avro messages for kafka and register schemas in schemaRepository.
5)planning to add producers for aws S3 and Redshift.

I didn't push those changes yet,will push them once I'm done with writing tests.

**Comment by mardambey** [comment]
The list of changes looks good (= Once you're done with tests please make sure the changes are well documented and split out into separate branches as much as possible. When it comes time to review your code I'd much rather be able to work with smaller chunks that can be modified (if needed) and merged in separately.

Thanks again for the effort! We all really appreciate your putting in time and energy into mypipe (=
