### ISSUE TITLE
issue with using  logback for slf4j

### ISSUE THREAD

**Issue by bbnsumanth** [mardambey/mypipe#33]
I'm trying to use logback for slf4j,but couldn't use it because of the following warning
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/mypipe/mypipe-avro/lib/avro-repo-bundle-1.7.5-1124-SNAPSHOT-withdeps.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]

Is there any way to remove org/slf4j/impl/StaticLoggerBinder.class from avro-repo-bundle-1.7.5-1124-SNAPSHOT-withdeps.jar.I don't know how to exclude slf4j dependency from avro-repo-bundle-1.7.5-1124-SNAPSHOT-withdeps.jar using sbt, since it was added manually.

Any help on this will be very useful.

**Comment by bbnsumanth** [comment]
following is my logback.xml file
[logback.txt](https://github.com/mardambey/mypipe/files/48499/logback.txt)

even though i'm using file appender in my logback.xml,,,all the logs are printed to console only.I'm guessing that slf4j is not binding to logback.

**Comment by FelixGV** [comment]
@mardambey,

You should depend on the schema-repo jars published in Maven Central ;)

That should allow finer-grained management of dependencies and transitive dependencies.

-F

**Comment by bbnsumanth** [comment]
I found a hack to force mypipe to use logback by copying StaticLoggerBinder class from logback to mypipe code.Since this class is encountered first,Slf4j will use this binding.

**Comment by mardambey** [comment]
This (666680f6dffd61a2c1384591677beb4f42fd06ac) will eventually help.

**Comment by mardambey** [comment]
See #36
