### ISSUE TITLE
Mypipe with AmazonRDS

### ISSUE THREAD

**Issue by bbnsumanth** [mardambey/mypipe#35]
Can I use mypipe to extract logs from Amazon RDS.If its possible,how can I achieve that.Any reference links will be highly helpfu

**Comment by mardambey** [comment]
See also https://github.com/shyiko/mysql-binlog-connector-java/issues/78.

**Comment by mardambey** [comment]
I don't use Amazon RDS myself, but perhaps someone else does and can help you out. Let us know what you find out if you try it out, you can use the [mailing](https://groups.google.com/forum/#!forum/mypipe) list.
