### ISSUE TITLE
Cannot change log level

### ISSUE THREAD

**Issue by tramchamploo** [mardambey/mypipe#36]
logback.xml is put in the wrong place, but after I move it to 'resources', it still didn't work.

**Comment by bbnsumanth** [comment]
@tramchamploo 
 we can  force mypipe to use logback by copying StaticLoggerBinder class from logback to mypipe code.Since this class is encountered first,Slf4j will use this binding.Look into issue #33 for more details.

**Comment by mardambey** [comment]
@tramchamploo @bbnsumanth see 2cd84a9bf00b780f59ba2a82df065d144e6fdf04, let me know the status on your side.

**Comment by ildac** [comment]
To make it work I had to move all the logback.xml files to resources folder as @tramchamploo said.
