### ISSUE TITLE
Modular binary log position saving 

### ISSUE THREAD

**Issue by mardambey** [mardambey/mypipe#40]
We can currently only save and load binary log positions to and from text files. The directory for these text files is configurable through the main application.conf.

We need to allow mypipe to save and load positions in a modular way so we can choose to store them in files, the MySQL database itself, a topic in Kafka, or some other place.

See #22 for some initial discussion.

**Comment by tramchamploo** [comment]
I've done it in my fork, with a implementation in zookeeper. Initially used to switch to another mysql instance when one is down, but different instances have different binlog files. 
That makes mysql switching impossible, when is it going to support consuming from a gtid?

**Comment by mardambey** [comment]
In master! (=
