### ISSUE TITLE
Is it possible to extend KafkaGenericMutationAvroConsumer with a java class

### ISSUE THREAD

**Issue by tramchamploo** [mardambey/mypipe#42]
For my colleges to use mypipe, I need to write a Java base consumer implementation.

**Comment by mardambey** [comment]
@tramchamploo what are the issues you're running into with this?

**Comment by tramchamploo** [comment]
I've made some tests, and prove Java consumer worked fine.

**Comment by rhamnett** [comment]
Any chance you can provide an example of this? Might be what I am looking for. Thanks
