### ISSUE TITLE
Skipping events cause empty mutation list.

### ISSUE THREAD

**Issue by tramchamploo** [mardambey/mypipe#43]
If specifying skipping some tables, mutations will not be added in txQueue. This will lead to commit failure.

**Comment by mardambey** [comment]
@tramchamploo, you should use a config similar to this so mypipe doesn't quit when it encounters an empty mutation list.

```
mypipe {
    include-event-condition = """ ... """
    error {
        quit-on-empty-mutation-commit-failure = false
    }
}
```

**Comment by tramchamploo** [comment]
But it still cause errors, so maybe skipping errors when skipping events.

**Comment by mardambey** [comment]
@tramchamploo can you send us your config + sample queries to get this to fail? For some reason the last reply you sent me was only in my email, nothing here on GitHub.

**Comment by tramchamploo** [comment]
I get this done, so never mind.
