### ISSUE TITLE
sbt launcher script fails due to old url

### ISSUE THREAD

**Issue by dr3s** [mardambey/mypipe#45]
http://typesafe.artifactoryonline.com/ is no longer valid and causes the error below.  I just install and run using a brew provided sbt instead.  

➜  mypipe git:(master) ✗ ./sbt
Downloading sbt launcher 0.13.8:
  From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
Download failed. Obtain the jar manually

**Comment by mardambey** [comment]
Thanks for the report.

Patched up and good to go for SBT 0.13.9.
