### ISSUE TITLE
How do you retrieve a map from the generic kafka structure

### ISSUE THREAD

**Issue by rhamnett** [mardambey/mypipe#51]
Hello, wondered if you could kindly help. I'm trying to retrieve a generic insert mutation message from a kafka queue which was posted to the queue using the kafka-generic mypipe.producer.KafkaMutationGenericAvroProducer 

The code I have below, is able to return an object but the object is just a string and does not have any dimensions to it, eg hashmap or similar where i can say result.get("myfield")

I am struggling to understand how to iterate through the data. Any help greatly appreciated.

```
public void run() {
        ConsumerIterator<byte[], byte[]> it = m_stream.iterator();
        while (it.hasNext()) {
            try {
                //System.out.println("Encoded Message received : " + message_received);
                //byte[] input = Hex.decodeHex(it.next().message().toString().toCharArray());
                //System.out.println("Deserializied Byte array : " + input);
                byte[] received_message = it.next().message();
                System.out.println(received_message);
                Schema schema = null;
                schema = new Schema.Parser().parse(new File("mutations.avsc"));
                DatumReader<GenericData.Fixed> reader = new GenericDatumReader<GenericData.Fixed>(schema);
                Decoder decoder = DecoderFactory.get().binaryDecoder(received_message, null);
                GenericData.Fixed payload2 = null;
                reader.setSchema(schema);
                payload2 = reader.read(null, decoder);
                System.out.println("Message received : " + payload2 + "schema "+payload2.getSchema());

            }catch (Exception e) {
                e.printStackTrace();
                System.out.println(e);
            }


        }
        System.out.println("Shutting down Thread: " + m_threadNumber);
    }
```

I am using the schema from your latest repo https://github.com/mardambey/mypipe/blob/70c692ddcc97deb4d95f914529d9c4380307bca9/mypipe-avro/src/main/avro/mutations.avsc

Thanks

**Comment by rhamnett** [comment]
To add to this, I did try to use a GenericRecord but the published type onto the queue appears to be GenericData.Fixed

java.lang.ClassCastException: org.apache.avro.generic.GenericData$Fixed cannot be cast to org.apache.avro.generic.GenericRecord

**Comment by mardambey** [comment]
@rhamnett take a look at:

https://github.com/mardambey/mypipe/blob/bb7acf47f9e80b8792b4ed517fa16d82763bd3c9/mypipe-kafka/src/main/scala/mypipe/kafka/consumer/GenericConsoleConsumer.scala

The Kafka messages do not just consist of the Avro data. They actually have a specific format which is documented [here](https://github.com/mardambey/mypipe#kafka-message-format).

You can use `KafkaGenericMutationAvroConsumer` by extending it, or you can read the bytes yourself to extract the Avro data before passing it to the `GenericDatumReader`.

**Comment by rhamnett** [comment]
Appreciate the reply. Still struggling to decode the messages coming from individual topics such as  database_table_generic. Do you have a java example of using the binary decoder on a kafka message with a generic record and existing schema? 

Many thanks

Richard

**Comment by mardambey** [comment]
@rhamnett Are you trying to do this totally on your own or making use of `KafkaGenericMutationAvroConsumer`?

If you do not use `KafkaGenericMutationAvroConsumer`, you have to decode the bytes yourself based on the docs I pointed to earlier, which I'll add here:

```
 -----------------
| MAGIC | 1 byte  |
|-----------------|
| MTYPE | 1 byte  |
|-----------------|
| SCMID | N bytes |
|-----------------|
| DATA  | N bytes |
 -----------------
```

The SCMID (schema id) is usually a short by default. So, you have to read 1 byte + 1 byte + 1 short, after which you'll have a byte array containing the Avro data you want. If you use `KafkaGenericMutationAvroConsumer`, all of this is done for you.

**Comment by rhamnett** [comment]
Hello, thanks again for the reply.

I am not sure the problem is that of the byte offsets, if I use the binarydecoder and a GenericDatumReader.Fixed type I am able to parse the payload.

However, if I replace GenericDatumReader.Fixed. with GenericDatumReader.Record then I get a cast exception. Thus I cannot get access to any of the fields that have been serialized.

I am possibly doing something wrong at an earlier stage eg setting up the schema in the original example I posted. I can definitely see all the data I would expect to be in the record if I dump the kafka message bytes.

Richard

**Comment by rhamnett** [comment]
Hex dump of the kafka data might help
`000100001a6f72636869645f73797374656d06636472c6fa02027256ac5cdf3d11e5883a005056a374970008106475726174696f6ef20f10616d61666c616773040e62696c6c736563de0f0e63616c6c5f69648006001a0664737418343432303337343034333630067372631630313631373932353637351064636f6e74657874346164696e73696768742d6469616c6f75742d65787465726e616c0e6368616e6e656c325349502f38372e3233382e37322e36382d303031306333616408636c696400106c61737464617461505349502f6d61677261746865612d6f7574626f756e642f30323037363635303030302c3630302c4316646973706f736974696f6e10414e53574552454412757365726669656c6400106f7574626f756e641630323037363635303030300e6c617374617070084469616c166163636f756e74636f6465083130353710756e69717565696436636c6172697479312d313435363738383035332e31303938353130146473746368616e6e656c3e5349502f6d61677261746865612d6f7574626f756e642d303031306333616500041e6e756d6265725f67726f75705f6964a2da111a72756c655f67726f75705f6964eafb2600`

**Comment by rhamnett** [comment]
I've created a full example class so it is easy for you to see what I am referring to:

http://pastebin.ca/3385426

Any help appreciated

**Comment by rhamnett** [comment]
InsertMutation.avsc   is here http://pastebin.ca/3385431

mypipe config used is here http://pastebin.ca/3385495

**Comment by mardambey** [comment]
@rhamnett cheers - I'll take a look at this as soon as I can.

**Comment by rhamnett** [comment]
@mardambey thanks, would really like to get to the bottom of this!

**Comment by rhamnett** [comment]
Any update on this? I haven't managed to get any further. Thanks in advance @mardambey

**Comment by mardambey** [comment]
@rhamnett I tried taking a look at your link: 

http://pastebin.ca/3385426

but it has expired. Reckon you can toss the code up somewhere else, perhaps in a Gist, so I can take a look?

**Comment by caojiaqing** [comment]
<p>

       public static final byte PROTO_MAGIC_V0 = Byte.parseByte("0");
       public static final byte UNKNOWNBYTE = Byte.parseByte("0")
       public static final byte INSERTBYTE = Byte.parseByte("1");
       public static final byte UPDATEBYTE = Byte.parseByte("2");
       public static final byte DELETEBYTE = Byte.parseByte("3");

        ......
        props.put("value.deserializer", ByteArrayDeserializer.class.getName());
        KafkaConsumer<byte[], byte[]> consumer = new KafkaConsumer<>(props);
        consumer.subscribe(Collections.singletonList("mypipe_user_generic"));
        while (true) {
            ConsumerRecords<byte[], byte[]> records = consumer.poll(10);
            for (ConsumerRecord<byte[], byte[]> record : records) {
                try {
                    Schema schema = new Schema.Parser().parse(new File("mutations.avsc"));
                    byte[] body = record.value();
                    byte magic = body[0];
                    if (magic != PROTO_MAGIC_V0) {
                        LOG.error("We have encountered an unknown magic byte! Magic Byte: {}", magic);
                    } else {
                        byte mutationType = body[1];
                        byte[] data = new byte[body.length - 4];
                        System.arraycopy(body, 4, data, 0, body.length - 4);
                        Decoder decoder = DecoderFactory.get().binaryDecoder(data, null);
                        DatumReader<GenericRecord> reader = null;
                        if (mutationType == INSERTBYTE) {
                            for (Schema s : schema.getTypes()) {
                                if (s.getName().equals("InsertMutation")) {
                                    reader = new GenericDatumReader<>(s);
                                    break;
                                }
                            }
                        }
                        if (mutationType == UPDATEBYTE) {
                            for (Schema s : schema.getTypes()) {
                                if (s.getName().equals("UpdateMutation")) {
                                    reader = new GenericDatumReader<>(s);
                                    break;
                                }
                            }
                        }
                        if (mutationType == DELETEBYTE) {
                            for (Schema s : schema.getTypes()) {
                                if (s.getName().equals("DeleteMutation")) {
                                    reader = new GenericDatumReader<>(s);
                                    break;
                                }
                            }
                        }
                        assert reader != null;
                        GenericRecord payload = reader.read(null, decoder);
                        LOG.info("Message received : " + payload);
                    }

                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
<p/>

**Comment by caojiaqing** [comment]
UP may be helpful for you @rhamnett

**Comment by yufeng0528** [comment]
@caojiaqing 大哥 你的东西还是报错啊
`Error while processing: ConsumerRecord(topic = xmall_customer_generic, partition = 0, offset = 40, CreateTime = -1, checksum = 498637550, serialized key size = -1, serialized value size = 407, key = null, value = java.lang.IllegalArgumentException
	at java.nio.ByteBuffer.allocate(Unknown Source)
	at org.apache.avro.io.BinaryDecoder.readBytes(BinaryDecoder.java:288)
	at org.apache.avro.io.ResolvingDecoder.readBytes(ResolvingDecoder.java:237)
	at org.apache.avro.generic.GenericDatum`

---------------------------------------------------------------------
ps the kafka consumer config must be "value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer"
