### ISSUE TITLE
[feature request] support for database topics

### ISSUE THREAD

**Issue by thomasdziedzic** [mardambey/mypipe#7]
Hello, I read in the readme that events get published to: "$database_$table_generic" topics.

I would like to use mypipe as the base for a heterogenous replication system.
I would like to preserve transactions when I translate changes form the source to the target.

In order to do this, I would need something like the topic: "$database_generic" so that transactions could be preserved across multiple tables.

Also a transaction id would probably be necessary in order to know what operations happened inside the same transaction so that I would be able to replicate the same transaction in the target database.

**Comment by mardambey** [comment]
@gostrc, commit 609b74316195f3f6891b0297124b0005dca99130 starts to address your request. It allows for the topic names to be customized.

**Comment by mardambey** [comment]
@gostrc, commit 0f34828d07a1cf620d610073e9347b1d6344aedb adds transaction aware UUIDs to the data.
